name: Java CI
on: [push]

jobs:
  jenkins-container-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2   # runs outside container

      - uses: jenkinsci/jfr-container-action@v1
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
